name: Keep Alive

on:
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Pinging the deployment
        run: |
          curl -X GET https://https://myfreewebgames.onrender.com/
